[project]
name = "skill-radar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ELAMINE Mohammed", email = "elamine.mohammed.14@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
skill-radar = "skill_radar:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
